- name: install grafana
  shell: |
    apt update
    apt install -y software-properties-common apt-transport-https
    wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
    add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
    apt update && apt install -y grafana
    systemctl enable --now grafana-server
